---
# This playbook contains common plays that will be run on all nodes.

- name: Ensure dns servers are configured in /etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf
  tags: [configuration,dns]


