- name: Add user deploy
  user:
    name=deploy
    password={{ password }}
    createhome=yes
    shell=/bin/bash

- name: Add SSH public key to user deploy
  authorized_key:
    user=deploy
    key="{{ lookup('file', "files/all_deploy.pub") }}"

- name: Add user deploy to sudoers
  lineinfile:
    "dest=/etc/sudoers
    regexp='^deploy ALL'
    line='deploy ALL=(ALL) NOPASSWD: ALL'
    state=present"